version: '3.8'

services:
  backend:
    build: ./airline-tracking-service
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  frontend:
    build: ./airline-tracking-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
